gabantonini/jarbas

config/environments/production.rb, config/initializers/devise.rb
so alterei alguns dados gerais para a configuraçao do devise ficar com nossas dados / infos do app. Nada de mais...
=> apenas algumas personalizacoes de configuracao do devise

.gitignore, Gemfile, Gemfile.lock, config/environments/development.rb, config/environments/production.rb, config/storage.yml
apenas configuração initial do cloundinary.
para usar em vossos PCs, so criar o arquivo .env e colocar vossa chave la. 
no heroku ja ta configurado. não precisa mudar nada.
=> Cloudinary setup

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/devise/registrations/new.html.erb, db/migrate/20200504150739_create_active_storage_tables.active_storage.rb, db/migrate/20200505212011_change_zip_code_to_be_string_in_users.rb, db/schema.rb, db/seeds.rb
@aurelien-jacomy  @gabantonini 
- Adicionei no user model:
- first_name
- last_name
- address
- zip_code
- validações necessárias 
- form de sign up pra rececber os atributos
- seed para 20 usuarios
- install do active_storage 
-fiquei um pouco na duvida se isso deveria ser feito aqui, mas como estava travando o seed sem isso, resolvi já fazer.
=> Added new attributes for UserModel, Form for Sign up,ActiveStorage and Seed

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html
Added this footer. Nothing fancy
=> Adding a footer with fake links

app/controllers/reviews_controller.rb, app/models/review.rb, db/migrate/20200507195637_create_reviews.rb, test/controllers/reviews_controller_test.rb, test/models/review_test.rb
Só criei o modelo, a migration e o controller, pois preciso de services para fazer funcionar.
=> Creating Review Model & Controller

app/views/services/index.html.erb, db/seeds.rb
Seed feito.
Deixei seed de 3 users e 2 a 5 servicos para cada pois aqui ta devagar para buscar cada imagem. Era para ver se tava funcionando a integracao com cloundinary. Mas depois pro seed que sabe melhor usar imagem ja local para ir mais rapido e ate a gente gerar mais user e sobretudo mais servicos para ir testando o layout como fica com pagina cheia...
=> Seed for users and services. Also showing photo of service on index

app/controllers/reviews_controller.rb, app/models/booking.rb, app/models/review.rb, app/models/service.rb, app/models/user.rb, app/views/reviews/edit.html.erb, app/views/reviews/new.html.erb, config/routes.rb
Added validation and association to review, user, booking and service
Added a new page
Added an edit page 
Need to refectories after the routes
=> Added reviews validation new and edit pages

app/controllers/bookings_controller.rb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/services/index.html.erb, config/routes.rb
@gabantonini @aurelien-jacomy 
- nestei as routes de booking
- criei a view de new booking (super simples por enquanto)
- view de show booking (também simples)
- controller de booking para essas ações
=> inicio da feature "como um user, posso bookar um servico"

db/schema.rb, db/seeds.rb
arrumei o seed para funcionar com todos os modelos apos os varios merge que fizemos.
testei aqui e ta funcionando apos um db:reset
=> seed working with all the models. Easier way to read when seeding

app/models/service.rb, app/views/services/show.html.erb
Vai ter problema de merge parece... 
Faz o average rating de um serviço, e mostra o valor na página show do service. Criei o metodo de class Service.rating
Não consegui fazer o join entre as tabelas, mas pelo menos funciona.
=> Added average rating feature to service model & page

app/controllers/services_controller.rb, app/views/shared/_navbar.html.erb, app/views/shared/_service_form.html.erb
Added the link in the search bar 
Service_category was missing in the new form. Added it and added the value in the strong params
=> Link to new service and add service category to new form

app/controllers/services_controller.rb, app/views/services/index.html.erb, app/views/shared/_search.html.erb, db/seeds.rb
- home page com placeholder na search bar
- ao submit, vai pro Index de Services e mostra apenas os servicos contendo o que foi buscado
- se nao tiver nenhuma busca, o Index de Service mostra tudo
- mudei o  Seed para Service colocando no nome do service a categoria. assim fica mais facil na demo de fazer a busca. pois antes so tinha qualquer verbo em ingles entao fica mais complicado de mostrar
home page:
Ao fazer uma busca com a palavra: Aula
Pagina de servicos sem nenhuma busca:
=> search bar looking for services containing the query

app/models/booking.rb, app/views/bookings/index.html.erb, app/views/shared/_flashes.html.erb
On the my_booking pages: 
- Show a link to add a review if the service has been done or canceled, and if there is no review yet. I build a method add_review? to check this
- Add a link to the review already made, with the rating
=> Added a review system to the my_bookings page

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb
@aurelien-jacomy  @gabantonini 
Acho que vale a gente rever esse fluxo depois, mas pelo menos os simples pra demo de hoje já tá criado
=> btn para confirmar/rejeitar/cancelar booking adicinado

app/views/services/index.html.erb, app/views/services/show.html.erb
On the show page: 
- Changed the message "Confira o que nossos usuários..." para "Nenhuma avaliação" quando não tem review
- Adicionei um botão para fazer o booking do serviço 
- Adicionei o rating do serviço, e coloquei comentários nos elementos de descrição 
On the index page: 
- Adicionei um link para o serviço 
- Adicionei o rating e os mesmos comentários
=> Changed message and improved show and index pages for service

app/controllers/bookings_controller.rb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb
@gabantonini  @aurelien-jacomy 
style não tá 100% ainda, mas já deu uma melhorada
=> função de edição no booking + style no index de bookings

db/seeds.rb
apenas criando um usuario de teste para evitar de termos que criar sempre novo user para login. e tb podemos ir criando o que queremos nele no heroku para na demo ter tudo que queremos mostrar
email de acesso: teste@antonini.co
senha: 123456
=> seed creating a test user

app/views/bookings/show.html.erb, app/views/services/index.html.erb, app/views/shared/_navbar.html.erb
Name in navbar
Can see the user photo but the upload doesn't work
Changed the show page to have directly the service name
=> few changes for demo

app/models/booking.rb
Nada ver com o nome da branch, sorry. Verifica se os bookings tem review ou não
=> fixing review notification

app/controllers/application_controller.rb, app/views/devise/registrations/edit.html.erb, app/views/shared/_navbar.html.erb
Fixed user picture: 
- Allow params 
- include picture in the navbar
- Allow to change the picture in the edit page and link to profile update in the navbar
Add searchbar to the navbar
Put the home link on the left with the icon
=> Fix navbar

app/models/service.rb, app/views/shared/_service_form.html.erb
Just added a validation so that disponibility is greater or equal to one. Couldn't find a way to block the negative numbers while filling the form. 
Added labels in Portuguese to the form 
Couldn't find an easy way to add a class to the upload button
=> Disponibility validation and new service form labels

app/views/bookings/show.html.erb
Added 3 links after booking is finished:
=> Links to Cancelar, Editar and Back to Bookings

app/controllers/services_controller.rb, app/views/shared/_navbar.html.erb, app/views/shared/_search.html.erb
Changed the variable @search in the index method to be able to render the search bar in the navbar
Added the value of the searcher according to the search (input_html)
=> Fixed search in navbar

app/controllers/services_controller.rb, app/views/services/index.html.erb, app/views/services/show.html.erb
Ola !!! 
Coloquei links de previous and next na show page de serviços: 
- Se o usuário entrou por uma página index com query, os links vão para o serviço anterior ou posterior dos resultados da query. Quando chega no final da lista, não tem mais link next / before (como na foto)
- Se o usuário entrou sem query, os links vão para o serviço de index anterior ou posterior
=> Links on show service page

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss
so separando o CSS relativo ao card da home (comentario @aurelien-jacomy no PR anterior)
@victoralbanezi
=> created card partial for a better CSS organization

app/controllers/bookings_controller.rb, app/views/bookings/edit.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, db/migrate/20200514222100_add_column_to_bookings.rb, db/schema.rb
Adicionei o campo comentário no booking
Mudei a view do new, edit e show para integrar o comentário
=> Added comment field to bookings

app/models/condominio.rb, app/models/user.rb, db/migrate/20200514225042_create_condominios.rb, db/migrate/20200514231246_add_condominio_ref_to_users.rb, db/schema.rb, db/seeds.rb, test/models/condominio_test.rb
modelo para condominio criado + o seed.
nao coloquei no campo de condominio no new e edit de usuario pois talvez melhor nao deixar o usuario se colocar em um condominio.
tambem nao coloquei validacao assim o user pode ou nao ter um condominio.
acho que o caminho poderia ser um admin/gestor de condominio add esse campo a um user. ai esse user terá um outro acesso/visão.
enfim, a ver como queremos usar depois esse modelo...
=> condominio model and seed done

app/views/bookings/index.html.erb, app/views/shared/_search.html.erb
=> Added turbolinks on forms
